### ISSUE TITLE
Mismatch in library properties and repo name

### ISSUE THREAD

**Issue by gerthalberg** [pschatzmann/arduino-audiokit#112]
### Problem Description

When using the name in the different references to the library or in the library properties there's a mismatch in the naming. The github repo is names: https://github.com/pschatzmann/arduino-**audiokit** The url in the properties and in the references to the library is https://github.com/pschatzmann/arduino-**audio-kit**

### Device Description

Not relevant

### Sketch

```cpp
Not relevamt
```

### Other Steps to Reproduce

Using the name in references or library properties will give an error trying to install it

### Provide your Version of the EP32 Arduino Core

Not related to problem

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
just committed a correction...
