### ISSUE TITLE
Which board to select in Arduino IDE

### ISSUE THREAD

**Issue by rjrajbir** [pschatzmann/arduino-audiokit#22]
Hello there,
I have[ ESP32 Audio Devkit](https://robu.in/product/esp32-audio-kit/) and I have downloaded this code but I am not able to compile this code, could you please let me which board should I select or how to add this board in board manager.

Best Regards
Rajbir

**Comment by rjrajbir** [comment]
I have shared the link

**Comment by rjrajbir** [comment]
![1652969763618](https://user-images.githubusercontent.com/46959108/169315661-72ea63c1-c00d-4cfa-a517-dce0cf0cc700.JPEG)

**Comment by pschatzmann** [comment]
A149 ? This is different then your original link.
I have never seen this before. I would try with option 5 first

**Comment by rjrajbir** [comment]
Alright, thank you for your help but I am asking for arduino IDE
![Esp32_board](https://user-images.githubusercontent.com/46959108/169509902-5246ca21-5d32-445b-a47d-172ab60fa4bf.jpg)

**Comment by pschatzmann** [comment]
In Frequently Ask Questions you can find:
Question: Which Board do I need to select?
Answer: If the board is based on an ESP32, use the ESP32 Dev Module. Only the esp32_s2_kaluga_1_v1_2 is based on an ESP32-S2!

**Comment by rjrajbir** [comment]
Ok, but it still gives the error
![1653110543685](https://user-images.githubusercontent.com/46959108/169637050-e10a7619-2be6-49ae-b351-922cda880202.JPEG)

**Comment by pschatzmann** [comment]
Your confusing me: I close this issue because it has been answered and you did not respond on your other issue
