### ISSUE TITLE
Showing SineWaveGenerator.h:45:20: error: 'result' is used uninitialized in this function [-Werror=uninitialized]              size_t result;

### ISSUE THREAD

**Issue by rjrajbir** [pschatzmann/arduino-audiokit#23]
![result_eror](https://user-images.githubusercontent.com/46959108/169510758-fa413a04-4fac-4fa3-96c0-0055c64132ec.jpg)

Showing type define error.

Please solve this issue.

BR
Rajbir

**Comment by pschatzmann** [comment]
Hmm, I can't reproduce you issue. 
Are you sure that you have selected ESP32 Dev Module as board ?
If you go to -> Tools -> Board -> Board Manager and Enter ESP32. What version are you using?
If you use the actual version you should see esp32 by Espressif Systems version 2.0.3

**Comment by rjrajbir** [comment]
![1653110543685](https://user-images.githubusercontent.com/46959108/169646512-973f8a19-94c6-4c65-a9ca-36c333533d69.JPEG)
This the board I am using.
![esp32_board_version](https://user-images.githubusercontent.com/46959108/169646594-e366bfb8-1226-40d5-ad98-fb5986c6e11c.JPG)
My latest board version is 1.0.6

ok, thank you for your quick response.

**Comment by rjrajbir** [comment]
Yes, you were right, my compiler warning was set to ALL, by setting it default it worked.
Thank you so much

**Comment by pschatzmann** [comment]
Still strange: on my systems I don't get any error even if the compiler setting is set to ALL...
