### ISSUE TITLE
Question: codec mode and input settings (line in)

### ISSUE THREAD

**Issue by IsiTapier** [pschatzmann/arduino-audiokit#6]
Why is LINE_IN in the audio_hal_codec_mode_t setting and not in the audio_hal_adc_input_t setting?
Isn't it possible to have AUDIO_HAL_CODEC_MODE_BOTH activated and still LINE_IN selected as Input source? (simultaneously doing line in and line out)

**Comment by pschatzmann** [comment]
These are different concepts. In audio_hal_codec_mode_t you specify if you do input or output or both and audio_hal_adc_input_t specifies the input from which device you receive the input.  

By the way audio_hal_adc_input_t does not work properly on the AudioKit...

**Comment by IsiTapier** [comment]
Oh good to know
Do you know whether it is working for the esp32 lyra-t?
And does it work if you set the audio_hal_codec_mode_t to AUDIO_HAL_CODEC_MODE_LINE_IN?

**Comment by pschatzmann** [comment]
I haven't tried. 
I recommend to use my [arduino-audio-tools](https://github.com/pschatzmann/arduino-audio-tools) project which uses this library and adds an easy to use layer on top of this and there are plenty of [examples](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-audiokit)...

**Comment by IsiTapier** [comment]
I wonder why in the Ai-thinker config, line in is set as an input and in your config it goes as a codec mode instead.
https://github.com/pschatzmann/arduino-audiokit/blob/main/src/audio_hal/audio_hal.h:
![grafik](https://user-images.githubusercontent.com/41296026/157494707-9acd741f-ccb7-45a0-8a07-79fad7b595b0.png)
https://github.com/Ai-Thinker-Open/ESP32-A1S-AudioKit/blob/master/ESP32_AC101_Driver/ai_thinker_audio_kit_v2_2/board_def.h:
![grafik](https://user-images.githubusercontent.com/41296026/157493780-97eabf60-2b44-4971-8639-a74b08955716.png)

**Comment by pierluigizagaria** [comment]
In my case I have a Audio kit (ES8388) 2974 and I cannot get line in audio. LINE_1 gives buzzing, LINE_2 only the on-board microphone. What can I do to debug this thing?

**Comment by pschatzmann** [comment]
https://www.pschatzmann.ch/home/2021/12/15/the-ai-thinker-audiokit-audio-input-bug/

**Comment by pierluigizagaria** [comment]
It's an open question then. In my case I don't event get the line in mixed. I've used a Y adapter for a headset, and nothing gets captured from the headset microphone. 
Thank for the fast answer!

**Comment by pschatzmann** [comment]
Maybe there is just not enough power ? 
I tested with an IPAD having the power 3/4 up...

**Comment by pierluigizagaria** [comment]
Tried to input sound from output of my pc with a jack to jack adapter. I get sound but is very distorted. I was trying to make a voip intercom with this board but is becoming more and more frustrating.

**Comment by pschatzmann** [comment]
If you need to connect the audiokit with the pc you could try to use Wifi or Bluetooth to transmit the audio...

**Comment by pierluigizagaria** [comment]
Oh no is just for the audio in test you suggested. But no luck at all

**Comment by pschatzmann** [comment]
Ah, so voip intercom should still be possible...

**Comment by pierluigizagaria** [comment]
I was thinking about using the SIP protocol so I can think about my intercom as a phone and send a key number code to open the door. got everything working except the microphone input with esp-adf.

**Comment by pschatzmann** [comment]
I haven't worked with ADF, but  I think that's strange: have you tried both AUDIO_HAL_ADC_INPUT_LINE1 and AUDIO_HAL_ADC_INPUT_LINE2 ?

**Comment by pierluigizagaria** [comment]
Line 2 works only for the built in microphone. Line 1 low volume buzzing.

**Comment by pschatzmann** [comment]
Is the built-in microphone not good enough ?

**Comment by pierluigizagaria** [comment]
With external jack I could take the intercom audio and pipe it into the board so it can send it to my phone and vice versa with the jack out.
I could do it even without jacks and solder wires, but this board has 2 jacks and I would like to make this crappy board do what it's built for..

**Comment by pschatzmann** [comment]
If you check the [comment from Uzmeyer](https://www.pschatzmann.ch/home/2021/12/15/the-ai-thinker-audiokit-audio-input-bug/): If I am correct, the only way to fix this is taking MIC2 out of the circuit, simplest by removing the coupling caps C19 and C20, then you would be left with a working stereo line-in on LIN2/RIN2 and mono microphone on LIN1+RIN1.

**Comment by pierluigizagaria** [comment]
What are the coupling caps? Sorry for the stupid question!

**Comment by pierluigizagaria** [comment]
I've removed the mic2 from the board and set the line 2. 
The line in with headset still doesn't work BUT mic1 captures audio if I plug the jack into the board line in.
This is driving me crazy.

**Comment by pierluigizagaria** [comment]
Desoldered the second mic too. The line2 with linein attached work in a strange way. 
If I use a Y adapter and plug a headset with microphone into the board, I can hear sound but the microphone doesn't work. HOWEVER If I put the headphone plug into che linein, my headset speaker act as a microphone!
What's happening?

**Comment by pschatzmann** [comment]
Are you using this kind of adapter ? https://www.digitec.ch/de/s1/product/inline-headset-adapter-015-m-einstiegsklasse-35mm-klinke-aux-audio-kabel-13348379?dbq=1&gclid=Cj0KCQjwwJuVBhCAARIsAOPwGAQ-8ttNQ2S3Vav528iSiG3mg4sS6qnpAja8LrXsTdyM5azyC0Kq2_YaAvtKEALw_wcB&gclsrc=aw.ds

**Comment by pschatzmann** [comment]
I tested with some earphones and when I plug them into Linein like you did, I don't get any output!
So, either your board (version) is messed up, or then signs on your headset are wrong...

**Comment by pschatzmann** [comment]
My gut feeling is that the output of the microphone is just not strong enough to be picked up. Can you test with another audio source. E.g. connect your mobile phone, play music and use full volume

**Comment by pierluigizagaria** [comment]
If I connect the headphone to the line in, the headset speakers act as a microphone and works!
It should not be a power problem!
