### ISSUE TITLE
Power management of ES8388 using audio-kit lib

### ISSUE THREAD

**Issue by HosseinKasaei** [pschatzmann/arduino-audiokit#77]
Hi,

I've designed a custom board including ES8388 and ESP32. My board is used for a BLE application and is supplied by a battery so the power management is very critical. I'm using audio-kit library and I want to be able to turn on ES8388 whenever is needed and turn it off most of the time to save power. Tried to use kit.end() but no luck. The current consumed in different situation is as follows :

1- kit is not configured in the main() : 48 mA
2- kit is configured in the main() and it's always turned on : 90 mA
3- kit is configured but I use kit.end() when a callback occurs and current drops to : 80 mA

I was expecting the current in 3 to be the same as 1. Is it something about ESP32? maybe running kit.begin() is turning on somethings in it that kit.end() won't turn them off? 
Another experiment was that I turned off the power of ES8388 (it is powered by a LDO) and the current increased up to 100mA ! so I think there is something wrong with the esp.

**Comment by HosseinKasaei** [comment]
Thanks I tested these methods and the results were actually very good !
I have 20mA decrease when es8388_pa_power(false) and 5mA when Wire1.end() is called which left me with a current consumption of 55mA. Still can be improved because I have around 46mA when ES8388 is not configured at all. I'll appreciate any another idea and if I found by myself I'll share it here. Thanks again :)

**Comment by pschatzmann** [comment]
So I suggest to set the logging to debug and check if es8388_deinit(void) is called. 
This should shut down the audio chip...

**Comment by HosseinKasaei** [comment]
Here is the log. es8388_deinit is called : 

![Capture](https://user-images.githubusercontent.com/91954107/232034188-5def47f7-6a20-4b13-bc24-7b1d24afa00d.PNG)

**Comment by pschatzmann** [comment]
I just double checked the code, this should also shut down the Wire1.end(), so I guess the 5 mA are just measuring differences.

I will add the shut down of the power amplifer into the end() method.

Apart from this I don't see where the difference could come from...

**Comment by pschatzmann** [comment]
Just another idea: if you do not use the SD drive make sure to deactivate it

**Comment by HosseinKasaei** [comment]
> Just another idea: if you do not use the SD drive make sure to deactivate it

Yea I have deactivated it already

**Comment by pschatzmann** [comment]
I am closing this issue because I don't see anything which could be wrong...
