### ISSUE TITLE
"hal/gpio_types.h: No such file or directory"

### ISSUE THREAD

**Issue by musiq021** [pschatzmann/arduino-audiokit#96]
With ESP32 Dev Module chosen, in Arduino IDE 1.8.15

**Comment by pschatzmann** [comment]
I can't reproduce your issue. Are you sure that you are using an actual ESP32 version ? If you check in your boards manager: the actual  version is 2.0.9!

If this is not the cause of your issue you will need to describe exactly what you are doing so that I can try to reproduce your issue..

**Comment by musiq021** [comment]
Yes, there was some strange disconnect with the ESP support installation. Removing and reinstalling fixed. Thank you.
